name: Generate

on: workflow_dispatch

jobs:
  build:
    env:
      CONDA_PREFIX: /usr/share/miniconda/

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: mamba-org/provision-with-micromamba@v15
      with:
        extra-specs: |
          python=3.9

    - name: Build
      shell: bash -l {0}
      run: |
        python .ci_support/run.py --username ${{ github.actor }} --token ${{ secrets.GH_TOKEN }} --githubrepo ${{ github.repository }} 
        cp .ci_support/readmetemplate.md README.md 
        cat packages.md >> README.md
